---
title: "Report"
author: "Tomas Lopez & Katia Cammisa"
date: "5/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load(file="finalEntry.RData")
library(plotrix)
library(ggplot2)
library(plotly)
```

## Informacion Basica General
```{r info, echo=FALSE}
par(mfrow=c(2,2))
#Status
statusTable <- table(finalEntry$Status) 
statusLabels <- names(statusTable)
statusPercentage <- round(statusTable/sum(statusTable)*100)
statusLabels <- paste(statusLabels, statusPercentage) # add percents to labels 
statusLabels <- paste(statusLabels,"%",sep="") # ad % to labels 
pie(statusTable,labels = statusLabels, main="Estado", col = c("#80F0F0", "#F08080"))

#Sex
sexTable <- table(finalEntry$Sex) 
sexLabels <- names(sexTable)
sexPercentage <- round(sexTable/sum(sexTable)*100)
sexLabels <- paste(sexLabels, sexPercentage) # add percents to labels 
sexLabels <- paste(sexLabels,"%",sep="") # ad % to labels 
pie(sexTable,labels = sexLabels, col = c("#E667AF","#0D58A6"), main="Sexo")

#Scholarship
scholarshipTable <- table(is.na(finalEntry$Scholarship)) 
scholarshipLabels <- c("Si","No")
scholarshipPercentage <- round(scholarshipTable/sum(scholarshipTable)*100)
scholarshipLabels <- paste(scholarshipLabels, scholarshipPercentage)
scholarshipLabels <- paste(scholarshipLabels,"%",sep="") 
pie(scholarshipTable,labels = scholarshipLabels, col=c("#66CDAA", "#CD6689"), main="Beca")

#Career
careerTable <- table(finalEntry$Career) 
careerLabels <- names(careerTable)
careerPercentage <- round(careerTable/sum(careerTable)*100)
careerLabels <- paste(careerLabels, careerPercentage) # add percents to labels 
careerLabels <- paste(careerLabels,"%",sep="") # ad % to labels 
pie(careerTable, labels = careerLabels, main="Career", col = c("#B0C4DE", "#DEB0C4", "#C4DEB0"))
```

## Curso de Ingreso elegido
```{r entry, echo=FALSE}
entryTable <- table(finalEntry$Entry) 
entryLabels <- names(entryTable)
entryPercentage <- round(entryTable/sum(entryTable)*100)
entryLabels <- paste(entryLabels, entryPercentage) # add percents to labels 
entryLabels <- paste(entryLabels,"%",sep="") # ad % to labels 
pie(entryTable,labels = entryLabels, col=c("#FFA07A", "#FAFF7A", "#97FF7A", "#7AFFC1", "#7AD9FF", "#7F7AFF", "#E37AFF", "#FF7AB8"), main="Entry")
```

## Estado dado el sexo
```{r Sex&Status, echo=FALSE}
sexStatusTable <- table(finalEntry$Status,finalEntry$Sex)
barplot(sexStatusTable, col=c("lightcoral","mediumseagreen"),legend = rownames(sexStatusTable))
```

## Carrera dado el sexo
```{r Sex&Career, echo=FALSE}
sexCareerTable <- table(finalEntry$Sex, finalEntry$Career)
barplot(sexCareerTable, col=c("#E667AF","#0D58A6"),legend = rownames(sexCareerTable))
```

## Estado por tipo de Curso de Ingreso
```{r Entry&Status, echo=FALSE}
entry <- finalEntry$Entry[which(!finalEntry$Entry == "Pase Universitario" & !finalEntry$Entry == "Directo")]
status <- finalEntry$Status[which(!finalEntry$Entry == "Pase Universitario" & !finalEntry$Entry == "Directo")]
entryStatusTable <- table(status, entry)
barplot(entryStatusTable, col=c("plum","darkcyan"),legend = rownames(entryStatusTable),xlim = c(0,6.5))
```

## Año de Ingreso por Sexo
```{r Cohort&Sex, echo=FALSE}
cohort <- finalEntry$Cohort[which(!finalEntry$Cohort == "2017")]
sex <- finalEntry$Sex[which(!finalEntry$Cohort == "2017")]
entryStatusTable <- table(sex, cohort)
barplot(entryStatusTable, col=c("#E667AF","#0D58A6"), legend = rownames(entryStatusTable), ylab = "Poblacion", xlab = "Año de Ingreso")
```

## Notas Curso de Ingreso {.tabset}

### Promedio{.tabset}
#### 2018
```{r Promedio2018, echo=FALSE}
sex <- finalEntry$Sex[which(finalEntry$Cohort == "2018")]
ICAverage <- finalEntry$IC.Average[which(finalEntry$Cohort == "2018")]
sexICAv <- table(sex, ICAverage)
perSexIcAv <- 100*prop.table(sexICAv,1)
barplot(perSexIcAv, col = c("#E667AF", "#0D58A6"), beside = TRUE, ylab = "Porcentaje", xlab = "Promedio", legend = rownames(sexICAv))
```

#### 2019
```{r Promedio2019, echo=FALSE}
sex <- finalEntry$Sex[which(finalEntry$Cohort == "2019")]
ICAverage <- finalEntry$IC.Average[which(finalEntry$Cohort == "2019")]
sexICAv <- table(sex, ICAverage)
perSexIcAv <- 100*prop.table(sexICAv,1)
barplot(perSexIcAv, col = c("#E667AF", "#0D58A6"), beside = TRUE, ylab = "Porcentaje", xlab = "Promedio", legend = rownames(sexICAv))
```

### Matematica {.tabset}
#### 2018
```{r Matematica2018, echo=FALSE}
par(mfrow=c(1,2))
sex <- finalEntry$Sex[which(finalEntry$Cohort == "2018")]
calMath <- finalEntry$Cal.Math[which(finalEntry$Cohort == "2018")]
sexCalMath <- table(sex,calMath)
perSexCalMath <- 100*prop.table(sexCalMath,1)
barplot(perSexCalMath,col = c("#E667AF", "#0D58A6"), beside = TRUE, legend = rownames(sexCalMath), xlab = "Examen", ylab = "Porcentaje")

recMath <- finalEntry$Rec.Math[which(finalEntry$Cohort == "2018")]
sexRecMath <- table(sex,recMath)
perSexRecMath <- 100*prop.table(sexRecMath,1)
barplot(perSexRecMath,col = c("#E667AF", "#0D58A6"), beside = TRUE, legend = rownames(sexRecMath), xlab = "Recuperatorio", ylab = "Porcentaje")
```

#### 2019
```{r Matematica2019, echo=FALSE}
par(mfrow=c(1,2))
sex <- finalEntry$Sex[which(finalEntry$Cohort == "2019")]
calMath <- finalEntry$Cal.Math[which(finalEntry$Cohort == "2019")]
sexCalMath <- table(sex,calMath)
perSexCalMath <- 100*prop.table(sexCalMath,1)
barplot(perSexCalMath,col = c("#E667AF", "#0D58A6"),beside = TRUE,legend = rownames(sexCalMath), xlab = "Examen", ylab = "Porcentaje")

recMath <- finalEntry$Rec.Math[which(finalEntry$Cohort == "2019")]
sexRecMath <- table(sex,recMath)
perSexRecMath <- 100*prop.table(sexRecMath,1)
barplot(perSexRecMath,col = c("#E667AF", "#0D58A6"),beside = TRUE,legend = rownames(sexRecMath), xlab = "Recuperatorio", ylab = "Porcentaje")
```

### Fisica {.tabset}
#### 2018
```{r Fisica2018, echo=FALSE}
par(mfrow=c(1,2))
sex <- finalEntry$Sex[which(finalEntry$Cohort == "2018")]
calPhysics <- finalEntry$Cal.Physics[which(finalEntry$Cohort == "2018")]
sexCalPhysics <- table(sex,calPhysics)
perSexCalPhysics <- 100*prop.table(sexCalPhysics,1)
barplot(perSexCalPhysics,col = c("#E667AF", "#0D58A6"),beside = TRUE,legend = rownames(sexCalPhysics), xlab = "Examen", ylab = "Porcentaje", ylim=c(0,45))

recPhysics <- finalEntry$Rec.Physics[which(finalEntry$Cohort == "2018")]
sexRecPhysics <- table(sex,recPhysics)
perSexRecPhysics <- 100*prop.table(sexRecPhysics,1)
barplot(perSexRecPhysics,col = c("#E667AF", "#0D58A6"),beside = TRUE,legend = rownames(sexRecPhysics), xlab = "Recuperatorio", ylab = "Porcentaje")
```

#### 2019
```{r Fisica2019, echo=FALSE}
par(mfrow=c(1,2))
sex <- finalEntry$Sex[which(finalEntry$Cohort == "2019")]
calPhysics <- finalEntry$Cal.Physics[which(finalEntry$Cohort == "2019")]
sexCalPhysics <- table(sex,calPhysics)
perSexCalPhysics <- 100*prop.table(sexCalPhysics,1)
barplot(perSexCalPhysics, col = c("#E667AF", "#0D58A6"), beside = TRUE, legend = rownames(sexCalPhysics), xlab = "Examen", ylab = "Porcentaje")

recPhysics <- finalEntry$Rec.Physics[which(finalEntry$Cohort == "2019")]
sexRecPhysics <- table(sex,recPhysics)
perSexRecPhysics <- 100*prop.table(sexRecPhysics,1)
barplot(perSexRecPhysics,col = c("#E667AF", "#0D58A6"),beside = TRUE, legend = rownames(sexRecPhysics), xlab = "Recuperatorio", ylab = "Porcentaje")
```



